ennumera: ennumera.c
	gcc -o ennumera.o ennumera.c
primos: primos.c
	gcc -o primos.o primos.c
testNum: ennumera
	./ennumera.o
testPrimos: primos
	./primos.o
pipe: ennumera primos
	./ennumera.o | ./primos.o | ./primos.o | ./primos.o | ./primos.o | ./primos.o | ./primos.o | ./primos.o | ./primos.o | ./primos.o | ./primos.o | ./primos.o | ./primos.o | ./primos.o | ./primos.o | ./primos.o | ./primos.o | ./primos.o | ./primos.o | ./primos.o | ./primos.o | ./primos.o | ./primos.o | ./primos.o | ./primos.o | ./primos.o

